### ISSUE TITLE
inherited_class_hash

### ISSUE THREAD

**Issue by s12chung** [FinalCAD/csv_row_model#37]
``` ruby
class Test
   inherited_class_hash :dynamic_columns
end

# to be the same as
class Test
   class << self
            # @return [Hash] column names mapped to their options
        def dynamic_columns
          inherited_class_var(:@_dynamic_columns, {}, :merge)
        end

        protected

        def merge_dynamic_columns(column_hash)
          @_dynamic_columns ||= {}
          deep_clear_class_cache(:@_dynamic_columns)
          @_dynamic_columns.merge!(column_hash)
        end
  end
end
```

**Comment by joel** [comment]
done?

**Comment by s12chung** [comment]
not yet.

**Comment by joel** [comment]
I guess it is => https://github.com/FinalCAD/csv_row_model/blob/master/lib/csv_row_model/model/dynamic_columns.rb#L34

**Comment by s12chung** [comment]
i want to implement: `inherited_class_hash :dynamic_columns` it's a little different :P

**Comment by joel** [comment]
:confused:

**Comment by s12chung** [comment]
what i mean is.... i want to make every call to: `inherited_class_var(<something>, {}, :merge)` DRY by defining class methods dynamically. we have it:
https://github.com/FinalCAD/csv_row_model/blob/2b4aa9f9af7b00d30ae0d5c151359ff00f1f3dd3/lib/csv_row_model/import/presenter.rb#L98-L98
https://github.com/FinalCAD/csv_row_model/blob/c6442f97e05fe80d88b2b43dd1fae4ba8814f38b/lib/csv_row_model/model/children.rb#L47-L47
https://github.com/FinalCAD/csv_row_model/blob/9a151e552a9a16c34ba36d3958da157cff84664d/lib/csv_row_model/model/columns.rb#L34-L34
