### ISSUE TITLE
Should format_cell() return non-strings?

### ISSUE THREAD

**Issue by s12chung** [FinalCAD/csv_row_model#76]
For Import, the problem right now is we have two places to parse:
- `format_cell()`
- `:parse` option/`:type` option

where the value of `format_cell()` is passed to `:parse`. The algo is here: https://github.com/FinalCAD/csv_row_model/blob/d9ff0140cf6ba6c3e7e2da542da5b0a1a5b741ee/lib/csv_row_model/import/cell.rb#L26-L31

However, when `format_cell()` returns a non-string, `:parse` is expecting a string. The problem is especially bad when `format_cell()` returns false.

It's nice to have `format_cell()` do some parsing, handling cases that `csv_row_model` hasn't provided (like `oui/non` and random formats). Also, `dynamic_column` doesn't provide a `:type` option.

Given that I don't want to support `v0.x` with new features. I propose:

For `v0.x`, handle the edge cases by changing:
- https://github.com/FinalCAD/csv_row_model/blob/15f1c3c24a4f1cb30450cf9182aa7e5b93d2cfb3/lib/csv_row_model/import/attributes.rb#L19-L19
  to: `s.TO_S =~ BooleanFormatValidator::FALSE_BOOLEAN_REGEX ? false : true`
- https://github.com/FinalCAD/csv_row_model/blob/15f1c3c24a4f1cb30450cf9182aa7e5b93d2cfb3/lib/csv_row_model/import/attributes.rb#L41-L41 to `if value == false || value.present?`.

Hack around letting people use `format_cell()` to return non-strings because `v0.x` does not have the tools to handle all cases.

For `v1.x`, we'll add these tools:
-  `dynamic_column`'s `:type` option
- allow a way to config parsing for existing and custom types:

``` ruby
CsvRowModel.config do |config|
  config.type_parsers = {
     Boolean => ->(s) {  s == /oui|yes|y|n/  },
    CustomType => (s) {  s ... } 
  }
end

# maybe add a :format option....
# like one format for Boolean is "yes/no" only and another "y/n" only.
# but the main idea is letting you configure this
```

This way we can restrict all parsing to using the `:type` or `:parse` option freely.

**Comment by ale7714** [comment]
👍 yeah it's a good plan

**Comment by joel** [comment]
👍
